/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as FilesRouteImport } from './routes/files'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConductorRouteImport } from './routes/conductor'
import { Route as AiHotboardRouteImport } from './routes/ai-hotboard'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as AiHotboardIndexRouteImport } from './routes/ai-hotboard/index'
import { Route as SettingsProvidersRouteImport } from './routes/settings/providers'
import { Route as SettingsMcpRouteImport } from './routes/settings/mcp'
import { Route as ChatSessionKeyRouteImport } from './routes/chat/$sessionKey'
import { Route as ApiWorkspaceRouteImport } from './routes/api/workspace'
import { Route as ApiWhoamiRouteImport } from './routes/api/whoami'
import { Route as ApiTerminalStreamRouteImport } from './routes/api/terminal-stream'
import { Route as ApiTerminalResizeRouteImport } from './routes/api/terminal-resize'
import { Route as ApiTerminalInputRouteImport } from './routes/api/terminal-input'
import { Route as ApiTerminalCloseRouteImport } from './routes/api/terminal-close'
import { Route as ApiStartHermesRouteImport } from './routes/api/start-hermes'
import { Route as ApiStartAgentRouteImport } from './routes/api/start-agent'
import { Route as ApiSkillsRouteImport } from './routes/api/skills'
import { Route as ApiSessionsRouteImport } from './routes/api/sessions'
import { Route as ApiSessionStatusRouteImport } from './routes/api/session-status'
import { Route as ApiSessionSendRouteImport } from './routes/api/session-send'
import { Route as ApiSessionHistoryRouteImport } from './routes/api/session-history'
import { Route as ApiSendStreamRouteImport } from './routes/api/send-stream'
import { Route as ApiSendRouteImport } from './routes/api/send'
import { Route as ApiPreviewFileRouteImport } from './routes/api/preview-file'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as ApiPathsRouteImport } from './routes/api/paths'
import { Route as ApiModelsRouteImport } from './routes/api/models'
import { Route as ApiMemoryRouteImport } from './routes/api/memory'
import { Route as ApiLocalProvidersRouteImport } from './routes/api/local-providers'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiHermesTasksAssigneesRouteImport } from './routes/api/hermes-tasks-assignees'
import { Route as ApiHermesTasksRouteImport } from './routes/api/hermes-tasks'
import { Route as ApiHermesJobsRouteImport } from './routes/api/hermes-jobs'
import { Route as ApiHermesConfigRouteImport } from './routes/api/hermes-config'
import { Route as ApiGatewayStatusRouteImport } from './routes/api/gateway-status'
import { Route as ApiFilesRouteImport } from './routes/api/files'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiCrewStatusRouteImport } from './routes/api/crew-status'
import { Route as ApiContextUsageRouteImport } from './routes/api/context-usage'
import { Route as ApiConnectionStatusRouteImport } from './routes/api/connection-status'
import { Route as ApiConductorStopRouteImport } from './routes/api/conductor-stop'
import { Route as ApiConductorSpawnRouteImport } from './routes/api/conductor-spawn'
import { Route as ApiChatEventsRouteImport } from './routes/api/chat-events'
import { Route as ApiAuthCheckRouteImport } from './routes/api/auth-check'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as AiHotboardUserRouteImport } from './routes/ai-hotboard/user'
import { Route as AiHotboardSystemRouteImport } from './routes/ai-hotboard/system'
import { Route as AiHotboardLogoutRouteImport } from './routes/ai-hotboard/logout'
import { Route as AiHotboardIterationRouteImport } from './routes/ai-hotboard/iteration'
import { Route as AuthFeishuCallbackRouteImport } from './routes/auth/feishu/callback'
import { Route as AuthEmailVerifyRouteImport } from './routes/auth/email/verify'
import { Route as ApiSourcesHealthRouteImport } from './routes/api/sources/health'
import { Route as ApiSkillsUninstallRouteImport } from './routes/api/skills/uninstall'
import { Route as ApiSkillsToggleRouteImport } from './routes/api/skills/toggle'
import { Route as ApiSkillsInstallRouteImport } from './routes/api/skills/install'
import { Route as ApiSkillsHubSearchRouteImport } from './routes/api/skills/hub-search'
import { Route as ApiSessionsSendRouteImport } from './routes/api/sessions/send'
import { Route as ApiProfilesUpdateRouteImport } from './routes/api/profiles/update'
import { Route as ApiProfilesRenameRouteImport } from './routes/api/profiles/rename'
import { Route as ApiProfilesReadRouteImport } from './routes/api/profiles/read'
import { Route as ApiProfilesListRouteImport } from './routes/api/profiles/list'
import { Route as ApiProfilesDeleteRouteImport } from './routes/api/profiles/delete'
import { Route as ApiProfilesCreateRouteImport } from './routes/api/profiles/create'
import { Route as ApiProfilesActivateRouteImport } from './routes/api/profiles/activate'
import { Route as ApiOauthPollTokenRouteImport } from './routes/api/oauth.poll-token'
import { Route as ApiOauthDeviceCodeRouteImport } from './routes/api/oauth.device-code'
import { Route as ApiModelInfoRouteImport } from './routes/api/model/info'
import { Route as ApiMemoryWriteRouteImport } from './routes/api/memory/write'
import { Route as ApiMemorySearchRouteImport } from './routes/api/memory/search'
import { Route as ApiMemoryReadRouteImport } from './routes/api/memory/read'
import { Route as ApiMemoryListRouteImport } from './routes/api/memory/list'
import { Route as ApiMcpServersRouteImport } from './routes/api/mcp/servers'
import { Route as ApiMcpReloadRouteImport } from './routes/api/mcp/reload'
import { Route as ApiKnowledgeSyncRouteImport } from './routes/api/knowledge/sync'
import { Route as ApiKnowledgeSearchRouteImport } from './routes/api/knowledge/search'
import { Route as ApiKnowledgeReadRouteImport } from './routes/api/knowledge/read'
import { Route as ApiKnowledgeListRouteImport } from './routes/api/knowledge/list'
import { Route as ApiKnowledgeGraphRouteImport } from './routes/api/knowledge/graph'
import { Route as ApiKnowledgeConfigRouteImport } from './routes/api/knowledge/config'
import { Route as ApiHotboardVoteRouteImport } from './routes/api/hotboard/vote'
import { Route as ApiHotboardStrategyRouteImport } from './routes/api/hotboard/strategy'
import { Route as ApiHotboardIntakeRouteImport } from './routes/api/hotboard/intake'
import { Route as ApiHotboardFeedRouteImport } from './routes/api/hotboard/feed'
import { Route as ApiHermesTasksTaskIdRouteImport } from './routes/api/hermes-tasks.$taskId'
import { Route as ApiHermesProxySplatRouteImport } from './routes/api/hermes-proxy/$'
import { Route as ApiHermesJobsJobIdRouteImport } from './routes/api/hermes-jobs.$jobId'
import { Route as ApiAuthPasswordRouteImport } from './routes/api/auth/password'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthEmailRouteImport } from './routes/api/auth/email'
import { Route as AiHotboardViewLowFollowerRouteImport } from './routes/ai-hotboard/view/low-follower'
import { Route as AiHotboardViewBookmarksRouteImport } from './routes/ai-hotboard/view/bookmarks'
import { Route as AiHotboardViewAllRouteImport } from './routes/ai-hotboard/view/all'
import { Route as AiHotboardStrategyLineRouteImport } from './routes/ai-hotboard/strategy/$line'
import { Route as AiHotboardSourcesHealthRouteImport } from './routes/ai-hotboard/sources/health'
import { Route as AiHotboardSourceSourceRouteImport } from './routes/ai-hotboard/source/$source'
import { Route as AiHotboardIntakeXiaojExecutionRouteImport } from './routes/ai-hotboard/intake/xiaoj-execution'
import { Route as AiHotboardIntakeHermesStrategyRouteImport } from './routes/ai-hotboard/intake/hermes-strategy'
import { Route as ApiSessionsSessionKeyStatusRouteImport } from './routes/api/sessions/$sessionKey.status'
import { Route as ApiSessionsSessionKeyActiveRunRouteImport } from './routes/api/sessions/$sessionKey.active-run'
import { Route as ApiHotboardZaraRefreshRouteImport } from './routes/api/hotboard/zara/refresh'
import { Route as ApiHotboardZaraFeedRouteImport } from './routes/api/hotboard/zara/feed'
import { Route as ApiHotboardWechatIngestRouteImport } from './routes/api/hotboard/wechat/ingest'
import { Route as ApiHotboardWechatFeedRouteImport } from './routes/api/hotboard/wechat/feed'
import { Route as ApiHotboardVoteAggregateRouteImport } from './routes/api/hotboard/vote/aggregate'

const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConductorRoute = ConductorRouteImport.update({
  id: '/conductor',
  path: '/conductor',
  getParentRoute: () => rootRouteImport,
} as any)
const AiHotboardRoute = AiHotboardRouteImport.update({
  id: '/ai-hotboard',
  path: '/ai-hotboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiHotboardIndexRoute = AiHotboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AiHotboardRoute,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMcpRoute = SettingsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatSessionKeyRoute = ChatSessionKeyRouteImport.update({
  id: '/chat/$sessionKey',
  path: '/chat/$sessionKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceRoute = ApiWorkspaceRouteImport.update({
  id: '/api/workspace',
  path: '/api/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhoamiRoute = ApiWhoamiRouteImport.update({
  id: '/api/whoami',
  path: '/api/whoami',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTerminalStreamRoute = ApiTerminalStreamRouteImport.update({
  id: '/api/terminal-stream',
  path: '/api/terminal-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTerminalResizeRoute = ApiTerminalResizeRouteImport.update({
  id: '/api/terminal-resize',
  path: '/api/terminal-resize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTerminalInputRoute = ApiTerminalInputRouteImport.update({
  id: '/api/terminal-input',
  path: '/api/terminal-input',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTerminalCloseRoute = ApiTerminalCloseRouteImport.update({
  id: '/api/terminal-close',
  path: '/api/terminal-close',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStartHermesRoute = ApiStartHermesRouteImport.update({
  id: '/api/start-hermes',
  path: '/api/start-hermes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStartAgentRoute = ApiStartAgentRouteImport.update({
  id: '/api/start-agent',
  path: '/api/start-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkillsRoute = ApiSkillsRouteImport.update({
  id: '/api/skills',
  path: '/api/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionStatusRoute = ApiSessionStatusRouteImport.update({
  id: '/api/session-status',
  path: '/api/session-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionSendRoute = ApiSessionSendRouteImport.update({
  id: '/api/session-send',
  path: '/api/session-send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionHistoryRoute = ApiSessionHistoryRouteImport.update({
  id: '/api/session-history',
  path: '/api/session-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendStreamRoute = ApiSendStreamRouteImport.update({
  id: '/api/send-stream',
  path: '/api/send-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendRoute = ApiSendRouteImport.update({
  id: '/api/send',
  path: '/api/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreviewFileRoute = ApiPreviewFileRouteImport.update({
  id: '/api/preview-file',
  path: '/api/preview-file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPathsRoute = ApiPathsRouteImport.update({
  id: '/api/paths',
  path: '/api/paths',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryRoute = ApiMemoryRouteImport.update({
  id: '/api/memory',
  path: '/api/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocalProvidersRoute = ApiLocalProvidersRouteImport.update({
  id: '/api/local-providers',
  path: '/api/local-providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesTasksAssigneesRoute = ApiHermesTasksAssigneesRouteImport.update({
  id: '/api/hermes-tasks-assignees',
  path: '/api/hermes-tasks-assignees',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesTasksRoute = ApiHermesTasksRouteImport.update({
  id: '/api/hermes-tasks',
  path: '/api/hermes-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesJobsRoute = ApiHermesJobsRouteImport.update({
  id: '/api/hermes-jobs',
  path: '/api/hermes-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesConfigRoute = ApiHermesConfigRouteImport.update({
  id: '/api/hermes-config',
  path: '/api/hermes-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGatewayStatusRoute = ApiGatewayStatusRouteImport.update({
  id: '/api/gateway-status',
  path: '/api/gateway-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrewStatusRoute = ApiCrewStatusRouteImport.update({
  id: '/api/crew-status',
  path: '/api/crew-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContextUsageRoute = ApiContextUsageRouteImport.update({
  id: '/api/context-usage',
  path: '/api/context-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectionStatusRoute = ApiConnectionStatusRouteImport.update({
  id: '/api/connection-status',
  path: '/api/connection-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConductorStopRoute = ApiConductorStopRouteImport.update({
  id: '/api/conductor-stop',
  path: '/api/conductor-stop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConductorSpawnRoute = ApiConductorSpawnRouteImport.update({
  id: '/api/conductor-spawn',
  path: '/api/conductor-spawn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatEventsRoute = ApiChatEventsRouteImport.update({
  id: '/api/chat-events',
  path: '/api/chat-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCheckRoute = ApiAuthCheckRouteImport.update({
  id: '/api/auth-check',
  path: '/api/auth-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiHotboardUserRoute = AiHotboardUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AiHotboardRoute,
} as any)
const AiHotboardSystemRoute = AiHotboardSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AiHotboardRoute,
} as any)
const AiHotboardLogoutRoute = AiHotboardLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AiHotboardRoute,
} as any)
const AiHotboardIterationRoute = AiHotboardIterationRouteImport.update({
  id: '/iteration',
  path: '/iteration',
  getParentRoute: () => AiHotboardRoute,
} as any)
const AuthFeishuCallbackRoute = AuthFeishuCallbackRouteImport.update({
  id: '/auth/feishu/callback',
  path: '/auth/feishu/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEmailVerifyRoute = AuthEmailVerifyRouteImport.update({
  id: '/auth/email/verify',
  path: '/auth/email/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSourcesHealthRoute = ApiSourcesHealthRouteImport.update({
  id: '/api/sources/health',
  path: '/api/sources/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkillsUninstallRoute = ApiSkillsUninstallRouteImport.update({
  id: '/uninstall',
  path: '/uninstall',
  getParentRoute: () => ApiSkillsRoute,
} as any)
const ApiSkillsToggleRoute = ApiSkillsToggleRouteImport.update({
  id: '/toggle',
  path: '/toggle',
  getParentRoute: () => ApiSkillsRoute,
} as any)
const ApiSkillsInstallRoute = ApiSkillsInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => ApiSkillsRoute,
} as any)
const ApiSkillsHubSearchRoute = ApiSkillsHubSearchRouteImport.update({
  id: '/hub-search',
  path: '/hub-search',
  getParentRoute: () => ApiSkillsRoute,
} as any)
const ApiSessionsSendRoute = ApiSessionsSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => ApiSessionsRoute,
} as any)
const ApiProfilesUpdateRoute = ApiProfilesUpdateRouteImport.update({
  id: '/api/profiles/update',
  path: '/api/profiles/update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilesRenameRoute = ApiProfilesRenameRouteImport.update({
  id: '/api/profiles/rename',
  path: '/api/profiles/rename',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilesReadRoute = ApiProfilesReadRouteImport.update({
  id: '/api/profiles/read',
  path: '/api/profiles/read',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilesListRoute = ApiProfilesListRouteImport.update({
  id: '/api/profiles/list',
  path: '/api/profiles/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilesDeleteRoute = ApiProfilesDeleteRouteImport.update({
  id: '/api/profiles/delete',
  path: '/api/profiles/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilesCreateRoute = ApiProfilesCreateRouteImport.update({
  id: '/api/profiles/create',
  path: '/api/profiles/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilesActivateRoute = ApiProfilesActivateRouteImport.update({
  id: '/api/profiles/activate',
  path: '/api/profiles/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthPollTokenRoute = ApiOauthPollTokenRouteImport.update({
  id: '/api/oauth/poll-token',
  path: '/api/oauth/poll-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthDeviceCodeRoute = ApiOauthDeviceCodeRouteImport.update({
  id: '/api/oauth/device-code',
  path: '/api/oauth/device-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelInfoRoute = ApiModelInfoRouteImport.update({
  id: '/api/model/info',
  path: '/api/model/info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryWriteRoute = ApiMemoryWriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => ApiMemoryRoute,
} as any)
const ApiMemorySearchRoute = ApiMemorySearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ApiMemoryRoute,
} as any)
const ApiMemoryReadRoute = ApiMemoryReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => ApiMemoryRoute,
} as any)
const ApiMemoryListRoute = ApiMemoryListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => ApiMemoryRoute,
} as any)
const ApiMcpServersRoute = ApiMcpServersRouteImport.update({
  id: '/api/mcp/servers',
  path: '/api/mcp/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpReloadRoute = ApiMcpReloadRouteImport.update({
  id: '/api/mcp/reload',
  path: '/api/mcp/reload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeSyncRoute = ApiKnowledgeSyncRouteImport.update({
  id: '/api/knowledge/sync',
  path: '/api/knowledge/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeSearchRoute = ApiKnowledgeSearchRouteImport.update({
  id: '/api/knowledge/search',
  path: '/api/knowledge/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeReadRoute = ApiKnowledgeReadRouteImport.update({
  id: '/api/knowledge/read',
  path: '/api/knowledge/read',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeListRoute = ApiKnowledgeListRouteImport.update({
  id: '/api/knowledge/list',
  path: '/api/knowledge/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeGraphRoute = ApiKnowledgeGraphRouteImport.update({
  id: '/api/knowledge/graph',
  path: '/api/knowledge/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeConfigRoute = ApiKnowledgeConfigRouteImport.update({
  id: '/api/knowledge/config',
  path: '/api/knowledge/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHotboardVoteRoute = ApiHotboardVoteRouteImport.update({
  id: '/api/hotboard/vote',
  path: '/api/hotboard/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHotboardStrategyRoute = ApiHotboardStrategyRouteImport.update({
  id: '/api/hotboard/strategy',
  path: '/api/hotboard/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHotboardIntakeRoute = ApiHotboardIntakeRouteImport.update({
  id: '/api/hotboard/intake',
  path: '/api/hotboard/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHotboardFeedRoute = ApiHotboardFeedRouteImport.update({
  id: '/api/hotboard/feed',
  path: '/api/hotboard/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesTasksTaskIdRoute = ApiHermesTasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => ApiHermesTasksRoute,
} as any)
const ApiHermesProxySplatRoute = ApiHermesProxySplatRouteImport.update({
  id: '/api/hermes-proxy/$',
  path: '/api/hermes-proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesJobsJobIdRoute = ApiHermesJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => ApiHermesJobsRoute,
} as any)
const ApiAuthPasswordRoute = ApiAuthPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => ApiAuthRoute,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => ApiAuthRoute,
} as any)
const ApiAuthEmailRoute = ApiAuthEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => ApiAuthRoute,
} as any)
const AiHotboardViewLowFollowerRoute =
  AiHotboardViewLowFollowerRouteImport.update({
    id: '/view/low-follower',
    path: '/view/low-follower',
    getParentRoute: () => AiHotboardRoute,
  } as any)
const AiHotboardViewBookmarksRoute = AiHotboardViewBookmarksRouteImport.update({
  id: '/view/bookmarks',
  path: '/view/bookmarks',
  getParentRoute: () => AiHotboardRoute,
} as any)
const AiHotboardViewAllRoute = AiHotboardViewAllRouteImport.update({
  id: '/view/all',
  path: '/view/all',
  getParentRoute: () => AiHotboardRoute,
} as any)
const AiHotboardStrategyLineRoute = AiHotboardStrategyLineRouteImport.update({
  id: '/strategy/$line',
  path: '/strategy/$line',
  getParentRoute: () => AiHotboardRoute,
} as any)
const AiHotboardSourcesHealthRoute = AiHotboardSourcesHealthRouteImport.update({
  id: '/sources/health',
  path: '/sources/health',
  getParentRoute: () => AiHotboardRoute,
} as any)
const AiHotboardSourceSourceRoute = AiHotboardSourceSourceRouteImport.update({
  id: '/source/$source',
  path: '/source/$source',
  getParentRoute: () => AiHotboardRoute,
} as any)
const AiHotboardIntakeXiaojExecutionRoute =
  AiHotboardIntakeXiaojExecutionRouteImport.update({
    id: '/intake/xiaoj-execution',
    path: '/intake/xiaoj-execution',
    getParentRoute: () => AiHotboardRoute,
  } as any)
const AiHotboardIntakeHermesStrategyRoute =
  AiHotboardIntakeHermesStrategyRouteImport.update({
    id: '/intake/hermes-strategy',
    path: '/intake/hermes-strategy',
    getParentRoute: () => AiHotboardRoute,
  } as any)
const ApiSessionsSessionKeyStatusRoute =
  ApiSessionsSessionKeyStatusRouteImport.update({
    id: '/$sessionKey/status',
    path: '/$sessionKey/status',
    getParentRoute: () => ApiSessionsRoute,
  } as any)
const ApiSessionsSessionKeyActiveRunRoute =
  ApiSessionsSessionKeyActiveRunRouteImport.update({
    id: '/$sessionKey/active-run',
    path: '/$sessionKey/active-run',
    getParentRoute: () => ApiSessionsRoute,
  } as any)
const ApiHotboardZaraRefreshRoute = ApiHotboardZaraRefreshRouteImport.update({
  id: '/api/hotboard/zara/refresh',
  path: '/api/hotboard/zara/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHotboardZaraFeedRoute = ApiHotboardZaraFeedRouteImport.update({
  id: '/api/hotboard/zara/feed',
  path: '/api/hotboard/zara/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHotboardWechatIngestRoute = ApiHotboardWechatIngestRouteImport.update({
  id: '/api/hotboard/wechat/ingest',
  path: '/api/hotboard/wechat/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHotboardWechatFeedRoute = ApiHotboardWechatFeedRouteImport.update({
  id: '/api/hotboard/wechat/feed',
  path: '/api/hotboard/wechat/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHotboardVoteAggregateRoute =
  ApiHotboardVoteAggregateRouteImport.update({
    id: '/aggregate',
    path: '/aggregate',
    getParentRoute: () => ApiHotboardVoteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/ai-hotboard': typeof AiHotboardRouteWithChildren
  '/conductor': typeof ConductorRoute
  '/dashboard': typeof DashboardRoute
  '/files': typeof FilesRoute
  '/jobs': typeof JobsRoute
  '/memory': typeof MemoryRoute
  '/operations': typeof OperationsRoute
  '/profiles': typeof ProfilesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/skills': typeof SkillsRoute
  '/tasks': typeof TasksRoute
  '/terminal': typeof TerminalRoute
  '/ai-hotboard/iteration': typeof AiHotboardIterationRoute
  '/ai-hotboard/logout': typeof AiHotboardLogoutRoute
  '/ai-hotboard/system': typeof AiHotboardSystemRoute
  '/ai-hotboard/user': typeof AiHotboardUserRoute
  '/api/auth': typeof ApiAuthRouteWithChildren
  '/api/auth-check': typeof ApiAuthCheckRoute
  '/api/chat-events': typeof ApiChatEventsRoute
  '/api/conductor-spawn': typeof ApiConductorSpawnRoute
  '/api/conductor-stop': typeof ApiConductorStopRoute
  '/api/connection-status': typeof ApiConnectionStatusRoute
  '/api/context-usage': typeof ApiContextUsageRoute
  '/api/crew-status': typeof ApiCrewStatusRoute
  '/api/events': typeof ApiEventsRoute
  '/api/files': typeof ApiFilesRoute
  '/api/gateway-status': typeof ApiGatewayStatusRoute
  '/api/hermes-config': typeof ApiHermesConfigRoute
  '/api/hermes-jobs': typeof ApiHermesJobsRouteWithChildren
  '/api/hermes-tasks': typeof ApiHermesTasksRouteWithChildren
  '/api/hermes-tasks-assignees': typeof ApiHermesTasksAssigneesRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/local-providers': typeof ApiLocalProvidersRoute
  '/api/memory': typeof ApiMemoryRouteWithChildren
  '/api/models': typeof ApiModelsRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/preview-file': typeof ApiPreviewFileRoute
  '/api/send': typeof ApiSendRoute
  '/api/send-stream': typeof ApiSendStreamRoute
  '/api/session-history': typeof ApiSessionHistoryRoute
  '/api/session-send': typeof ApiSessionSendRoute
  '/api/session-status': typeof ApiSessionStatusRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/skills': typeof ApiSkillsRouteWithChildren
  '/api/start-agent': typeof ApiStartAgentRoute
  '/api/start-hermes': typeof ApiStartHermesRoute
  '/api/terminal-close': typeof ApiTerminalCloseRoute
  '/api/terminal-input': typeof ApiTerminalInputRoute
  '/api/terminal-resize': typeof ApiTerminalResizeRoute
  '/api/terminal-stream': typeof ApiTerminalStreamRoute
  '/api/whoami': typeof ApiWhoamiRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/ai-hotboard/': typeof AiHotboardIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/ai-hotboard/intake/hermes-strategy': typeof AiHotboardIntakeHermesStrategyRoute
  '/ai-hotboard/intake/xiaoj-execution': typeof AiHotboardIntakeXiaojExecutionRoute
  '/ai-hotboard/source/$source': typeof AiHotboardSourceSourceRoute
  '/ai-hotboard/sources/health': typeof AiHotboardSourcesHealthRoute
  '/ai-hotboard/strategy/$line': typeof AiHotboardStrategyLineRoute
  '/ai-hotboard/view/all': typeof AiHotboardViewAllRoute
  '/ai-hotboard/view/bookmarks': typeof AiHotboardViewBookmarksRoute
  '/ai-hotboard/view/low-follower': typeof AiHotboardViewLowFollowerRoute
  '/api/auth/email': typeof ApiAuthEmailRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/password': typeof ApiAuthPasswordRoute
  '/api/hermes-jobs/$jobId': typeof ApiHermesJobsJobIdRoute
  '/api/hermes-proxy/$': typeof ApiHermesProxySplatRoute
  '/api/hermes-tasks/$taskId': typeof ApiHermesTasksTaskIdRoute
  '/api/hotboard/feed': typeof ApiHotboardFeedRoute
  '/api/hotboard/intake': typeof ApiHotboardIntakeRoute
  '/api/hotboard/strategy': typeof ApiHotboardStrategyRoute
  '/api/hotboard/vote': typeof ApiHotboardVoteRouteWithChildren
  '/api/knowledge/config': typeof ApiKnowledgeConfigRoute
  '/api/knowledge/graph': typeof ApiKnowledgeGraphRoute
  '/api/knowledge/list': typeof ApiKnowledgeListRoute
  '/api/knowledge/read': typeof ApiKnowledgeReadRoute
  '/api/knowledge/search': typeof ApiKnowledgeSearchRoute
  '/api/knowledge/sync': typeof ApiKnowledgeSyncRoute
  '/api/mcp/reload': typeof ApiMcpReloadRoute
  '/api/mcp/servers': typeof ApiMcpServersRoute
  '/api/memory/list': typeof ApiMemoryListRoute
  '/api/memory/read': typeof ApiMemoryReadRoute
  '/api/memory/search': typeof ApiMemorySearchRoute
  '/api/memory/write': typeof ApiMemoryWriteRoute
  '/api/model/info': typeof ApiModelInfoRoute
  '/api/oauth/device-code': typeof ApiOauthDeviceCodeRoute
  '/api/oauth/poll-token': typeof ApiOauthPollTokenRoute
  '/api/profiles/activate': typeof ApiProfilesActivateRoute
  '/api/profiles/create': typeof ApiProfilesCreateRoute
  '/api/profiles/delete': typeof ApiProfilesDeleteRoute
  '/api/profiles/list': typeof ApiProfilesListRoute
  '/api/profiles/read': typeof ApiProfilesReadRoute
  '/api/profiles/rename': typeof ApiProfilesRenameRoute
  '/api/profiles/update': typeof ApiProfilesUpdateRoute
  '/api/sessions/send': typeof ApiSessionsSendRoute
  '/api/skills/hub-search': typeof ApiSkillsHubSearchRoute
  '/api/skills/install': typeof ApiSkillsInstallRoute
  '/api/skills/toggle': typeof ApiSkillsToggleRoute
  '/api/skills/uninstall': typeof ApiSkillsUninstallRoute
  '/api/sources/health': typeof ApiSourcesHealthRoute
  '/auth/email/verify': typeof AuthEmailVerifyRoute
  '/auth/feishu/callback': typeof AuthFeishuCallbackRoute
  '/api/hotboard/vote/aggregate': typeof ApiHotboardVoteAggregateRoute
  '/api/hotboard/wechat/feed': typeof ApiHotboardWechatFeedRoute
  '/api/hotboard/wechat/ingest': typeof ApiHotboardWechatIngestRoute
  '/api/hotboard/zara/feed': typeof ApiHotboardZaraFeedRoute
  '/api/hotboard/zara/refresh': typeof ApiHotboardZaraRefreshRoute
  '/api/sessions/$sessionKey/active-run': typeof ApiSessionsSessionKeyActiveRunRoute
  '/api/sessions/$sessionKey/status': typeof ApiSessionsSessionKeyStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/conductor': typeof ConductorRoute
  '/dashboard': typeof DashboardRoute
  '/files': typeof FilesRoute
  '/jobs': typeof JobsRoute
  '/memory': typeof MemoryRoute
  '/operations': typeof OperationsRoute
  '/profiles': typeof ProfilesRoute
  '/skills': typeof SkillsRoute
  '/tasks': typeof TasksRoute
  '/terminal': typeof TerminalRoute
  '/ai-hotboard/iteration': typeof AiHotboardIterationRoute
  '/ai-hotboard/logout': typeof AiHotboardLogoutRoute
  '/ai-hotboard/system': typeof AiHotboardSystemRoute
  '/ai-hotboard/user': typeof AiHotboardUserRoute
  '/api/auth': typeof ApiAuthRouteWithChildren
  '/api/auth-check': typeof ApiAuthCheckRoute
  '/api/chat-events': typeof ApiChatEventsRoute
  '/api/conductor-spawn': typeof ApiConductorSpawnRoute
  '/api/conductor-stop': typeof ApiConductorStopRoute
  '/api/connection-status': typeof ApiConnectionStatusRoute
  '/api/context-usage': typeof ApiContextUsageRoute
  '/api/crew-status': typeof ApiCrewStatusRoute
  '/api/events': typeof ApiEventsRoute
  '/api/files': typeof ApiFilesRoute
  '/api/gateway-status': typeof ApiGatewayStatusRoute
  '/api/hermes-config': typeof ApiHermesConfigRoute
  '/api/hermes-jobs': typeof ApiHermesJobsRouteWithChildren
  '/api/hermes-tasks': typeof ApiHermesTasksRouteWithChildren
  '/api/hermes-tasks-assignees': typeof ApiHermesTasksAssigneesRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/local-providers': typeof ApiLocalProvidersRoute
  '/api/memory': typeof ApiMemoryRouteWithChildren
  '/api/models': typeof ApiModelsRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/preview-file': typeof ApiPreviewFileRoute
  '/api/send': typeof ApiSendRoute
  '/api/send-stream': typeof ApiSendStreamRoute
  '/api/session-history': typeof ApiSessionHistoryRoute
  '/api/session-send': typeof ApiSessionSendRoute
  '/api/session-status': typeof ApiSessionStatusRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/skills': typeof ApiSkillsRouteWithChildren
  '/api/start-agent': typeof ApiStartAgentRoute
  '/api/start-hermes': typeof ApiStartHermesRoute
  '/api/terminal-close': typeof ApiTerminalCloseRoute
  '/api/terminal-input': typeof ApiTerminalInputRoute
  '/api/terminal-resize': typeof ApiTerminalResizeRoute
  '/api/terminal-stream': typeof ApiTerminalStreamRoute
  '/api/whoami': typeof ApiWhoamiRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/ai-hotboard': typeof AiHotboardIndexRoute
  '/chat': typeof ChatIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/ai-hotboard/intake/hermes-strategy': typeof AiHotboardIntakeHermesStrategyRoute
  '/ai-hotboard/intake/xiaoj-execution': typeof AiHotboardIntakeXiaojExecutionRoute
  '/ai-hotboard/source/$source': typeof AiHotboardSourceSourceRoute
  '/ai-hotboard/sources/health': typeof AiHotboardSourcesHealthRoute
  '/ai-hotboard/strategy/$line': typeof AiHotboardStrategyLineRoute
  '/ai-hotboard/view/all': typeof AiHotboardViewAllRoute
  '/ai-hotboard/view/bookmarks': typeof AiHotboardViewBookmarksRoute
  '/ai-hotboard/view/low-follower': typeof AiHotboardViewLowFollowerRoute
  '/api/auth/email': typeof ApiAuthEmailRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/password': typeof ApiAuthPasswordRoute
  '/api/hermes-jobs/$jobId': typeof ApiHermesJobsJobIdRoute
  '/api/hermes-proxy/$': typeof ApiHermesProxySplatRoute
  '/api/hermes-tasks/$taskId': typeof ApiHermesTasksTaskIdRoute
  '/api/hotboard/feed': typeof ApiHotboardFeedRoute
  '/api/hotboard/intake': typeof ApiHotboardIntakeRoute
  '/api/hotboard/strategy': typeof ApiHotboardStrategyRoute
  '/api/hotboard/vote': typeof ApiHotboardVoteRouteWithChildren
  '/api/knowledge/config': typeof ApiKnowledgeConfigRoute
  '/api/knowledge/graph': typeof ApiKnowledgeGraphRoute
  '/api/knowledge/list': typeof ApiKnowledgeListRoute
  '/api/knowledge/read': typeof ApiKnowledgeReadRoute
  '/api/knowledge/search': typeof ApiKnowledgeSearchRoute
  '/api/knowledge/sync': typeof ApiKnowledgeSyncRoute
  '/api/mcp/reload': typeof ApiMcpReloadRoute
  '/api/mcp/servers': typeof ApiMcpServersRoute
  '/api/memory/list': typeof ApiMemoryListRoute
  '/api/memory/read': typeof ApiMemoryReadRoute
  '/api/memory/search': typeof ApiMemorySearchRoute
  '/api/memory/write': typeof ApiMemoryWriteRoute
  '/api/model/info': typeof ApiModelInfoRoute
  '/api/oauth/device-code': typeof ApiOauthDeviceCodeRoute
  '/api/oauth/poll-token': typeof ApiOauthPollTokenRoute
  '/api/profiles/activate': typeof ApiProfilesActivateRoute
  '/api/profiles/create': typeof ApiProfilesCreateRoute
  '/api/profiles/delete': typeof ApiProfilesDeleteRoute
  '/api/profiles/list': typeof ApiProfilesListRoute
  '/api/profiles/read': typeof ApiProfilesReadRoute
  '/api/profiles/rename': typeof ApiProfilesRenameRoute
  '/api/profiles/update': typeof ApiProfilesUpdateRoute
  '/api/sessions/send': typeof ApiSessionsSendRoute
  '/api/skills/hub-search': typeof ApiSkillsHubSearchRoute
  '/api/skills/install': typeof ApiSkillsInstallRoute
  '/api/skills/toggle': typeof ApiSkillsToggleRoute
  '/api/skills/uninstall': typeof ApiSkillsUninstallRoute
  '/api/sources/health': typeof ApiSourcesHealthRoute
  '/auth/email/verify': typeof AuthEmailVerifyRoute
  '/auth/feishu/callback': typeof AuthFeishuCallbackRoute
  '/api/hotboard/vote/aggregate': typeof ApiHotboardVoteAggregateRoute
  '/api/hotboard/wechat/feed': typeof ApiHotboardWechatFeedRoute
  '/api/hotboard/wechat/ingest': typeof ApiHotboardWechatIngestRoute
  '/api/hotboard/zara/feed': typeof ApiHotboardZaraFeedRoute
  '/api/hotboard/zara/refresh': typeof ApiHotboardZaraRefreshRoute
  '/api/sessions/$sessionKey/active-run': typeof ApiSessionsSessionKeyActiveRunRoute
  '/api/sessions/$sessionKey/status': typeof ApiSessionsSessionKeyStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/ai-hotboard': typeof AiHotboardRouteWithChildren
  '/conductor': typeof ConductorRoute
  '/dashboard': typeof DashboardRoute
  '/files': typeof FilesRoute
  '/jobs': typeof JobsRoute
  '/memory': typeof MemoryRoute
  '/operations': typeof OperationsRoute
  '/profiles': typeof ProfilesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/skills': typeof SkillsRoute
  '/tasks': typeof TasksRoute
  '/terminal': typeof TerminalRoute
  '/ai-hotboard/iteration': typeof AiHotboardIterationRoute
  '/ai-hotboard/logout': typeof AiHotboardLogoutRoute
  '/ai-hotboard/system': typeof AiHotboardSystemRoute
  '/ai-hotboard/user': typeof AiHotboardUserRoute
  '/api/auth': typeof ApiAuthRouteWithChildren
  '/api/auth-check': typeof ApiAuthCheckRoute
  '/api/chat-events': typeof ApiChatEventsRoute
  '/api/conductor-spawn': typeof ApiConductorSpawnRoute
  '/api/conductor-stop': typeof ApiConductorStopRoute
  '/api/connection-status': typeof ApiConnectionStatusRoute
  '/api/context-usage': typeof ApiContextUsageRoute
  '/api/crew-status': typeof ApiCrewStatusRoute
  '/api/events': typeof ApiEventsRoute
  '/api/files': typeof ApiFilesRoute
  '/api/gateway-status': typeof ApiGatewayStatusRoute
  '/api/hermes-config': typeof ApiHermesConfigRoute
  '/api/hermes-jobs': typeof ApiHermesJobsRouteWithChildren
  '/api/hermes-tasks': typeof ApiHermesTasksRouteWithChildren
  '/api/hermes-tasks-assignees': typeof ApiHermesTasksAssigneesRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/local-providers': typeof ApiLocalProvidersRoute
  '/api/memory': typeof ApiMemoryRouteWithChildren
  '/api/models': typeof ApiModelsRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/ping': typeof ApiPingRoute
  '/api/preview-file': typeof ApiPreviewFileRoute
  '/api/send': typeof ApiSendRoute
  '/api/send-stream': typeof ApiSendStreamRoute
  '/api/session-history': typeof ApiSessionHistoryRoute
  '/api/session-send': typeof ApiSessionSendRoute
  '/api/session-status': typeof ApiSessionStatusRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/skills': typeof ApiSkillsRouteWithChildren
  '/api/start-agent': typeof ApiStartAgentRoute
  '/api/start-hermes': typeof ApiStartHermesRoute
  '/api/terminal-close': typeof ApiTerminalCloseRoute
  '/api/terminal-input': typeof ApiTerminalInputRoute
  '/api/terminal-resize': typeof ApiTerminalResizeRoute
  '/api/terminal-stream': typeof ApiTerminalStreamRoute
  '/api/whoami': typeof ApiWhoamiRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/ai-hotboard/': typeof AiHotboardIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/ai-hotboard/intake/hermes-strategy': typeof AiHotboardIntakeHermesStrategyRoute
  '/ai-hotboard/intake/xiaoj-execution': typeof AiHotboardIntakeXiaojExecutionRoute
  '/ai-hotboard/source/$source': typeof AiHotboardSourceSourceRoute
  '/ai-hotboard/sources/health': typeof AiHotboardSourcesHealthRoute
  '/ai-hotboard/strategy/$line': typeof AiHotboardStrategyLineRoute
  '/ai-hotboard/view/all': typeof AiHotboardViewAllRoute
  '/ai-hotboard/view/bookmarks': typeof AiHotboardViewBookmarksRoute
  '/ai-hotboard/view/low-follower': typeof AiHotboardViewLowFollowerRoute
  '/api/auth/email': typeof ApiAuthEmailRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/password': typeof ApiAuthPasswordRoute
  '/api/hermes-jobs/$jobId': typeof ApiHermesJobsJobIdRoute
  '/api/hermes-proxy/$': typeof ApiHermesProxySplatRoute
  '/api/hermes-tasks/$taskId': typeof ApiHermesTasksTaskIdRoute
  '/api/hotboard/feed': typeof ApiHotboardFeedRoute
  '/api/hotboard/intake': typeof ApiHotboardIntakeRoute
  '/api/hotboard/strategy': typeof ApiHotboardStrategyRoute
  '/api/hotboard/vote': typeof ApiHotboardVoteRouteWithChildren
  '/api/knowledge/config': typeof ApiKnowledgeConfigRoute
  '/api/knowledge/graph': typeof ApiKnowledgeGraphRoute
  '/api/knowledge/list': typeof ApiKnowledgeListRoute
  '/api/knowledge/read': typeof ApiKnowledgeReadRoute
  '/api/knowledge/search': typeof ApiKnowledgeSearchRoute
  '/api/knowledge/sync': typeof ApiKnowledgeSyncRoute
  '/api/mcp/reload': typeof ApiMcpReloadRoute
  '/api/mcp/servers': typeof ApiMcpServersRoute
  '/api/memory/list': typeof ApiMemoryListRoute
  '/api/memory/read': typeof ApiMemoryReadRoute
  '/api/memory/search': typeof ApiMemorySearchRoute
  '/api/memory/write': typeof ApiMemoryWriteRoute
  '/api/model/info': typeof ApiModelInfoRoute
  '/api/oauth/device-code': typeof ApiOauthDeviceCodeRoute
  '/api/oauth/poll-token': typeof ApiOauthPollTokenRoute
  '/api/profiles/activate': typeof ApiProfilesActivateRoute
  '/api/profiles/create': typeof ApiProfilesCreateRoute
  '/api/profiles/delete': typeof ApiProfilesDeleteRoute
  '/api/profiles/list': typeof ApiProfilesListRoute
  '/api/profiles/read': typeof ApiProfilesReadRoute
  '/api/profiles/rename': typeof ApiProfilesRenameRoute
  '/api/profiles/update': typeof ApiProfilesUpdateRoute
  '/api/sessions/send': typeof ApiSessionsSendRoute
  '/api/skills/hub-search': typeof ApiSkillsHubSearchRoute
  '/api/skills/install': typeof ApiSkillsInstallRoute
  '/api/skills/toggle': typeof ApiSkillsToggleRoute
  '/api/skills/uninstall': typeof ApiSkillsUninstallRoute
  '/api/sources/health': typeof ApiSourcesHealthRoute
  '/auth/email/verify': typeof AuthEmailVerifyRoute
  '/auth/feishu/callback': typeof AuthFeishuCallbackRoute
  '/api/hotboard/vote/aggregate': typeof ApiHotboardVoteAggregateRoute
  '/api/hotboard/wechat/feed': typeof ApiHotboardWechatFeedRoute
  '/api/hotboard/wechat/ingest': typeof ApiHotboardWechatIngestRoute
  '/api/hotboard/zara/feed': typeof ApiHotboardZaraFeedRoute
  '/api/hotboard/zara/refresh': typeof ApiHotboardZaraRefreshRoute
  '/api/sessions/$sessionKey/active-run': typeof ApiSessionsSessionKeyActiveRunRoute
  '/api/sessions/$sessionKey/status': typeof ApiSessionsSessionKeyStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/ai-hotboard'
    | '/conductor'
    | '/dashboard'
    | '/files'
    | '/jobs'
    | '/memory'
    | '/operations'
    | '/profiles'
    | '/settings'
    | '/skills'
    | '/tasks'
    | '/terminal'
    | '/ai-hotboard/iteration'
    | '/ai-hotboard/logout'
    | '/ai-hotboard/system'
    | '/ai-hotboard/user'
    | '/api/auth'
    | '/api/auth-check'
    | '/api/chat-events'
    | '/api/conductor-spawn'
    | '/api/conductor-stop'
    | '/api/connection-status'
    | '/api/context-usage'
    | '/api/crew-status'
    | '/api/events'
    | '/api/files'
    | '/api/gateway-status'
    | '/api/hermes-config'
    | '/api/hermes-jobs'
    | '/api/hermes-tasks'
    | '/api/hermes-tasks-assignees'
    | '/api/history'
    | '/api/local-providers'
    | '/api/memory'
    | '/api/models'
    | '/api/paths'
    | '/api/ping'
    | '/api/preview-file'
    | '/api/send'
    | '/api/send-stream'
    | '/api/session-history'
    | '/api/session-send'
    | '/api/session-status'
    | '/api/sessions'
    | '/api/skills'
    | '/api/start-agent'
    | '/api/start-hermes'
    | '/api/terminal-close'
    | '/api/terminal-input'
    | '/api/terminal-resize'
    | '/api/terminal-stream'
    | '/api/whoami'
    | '/api/workspace'
    | '/chat/$sessionKey'
    | '/settings/mcp'
    | '/settings/providers'
    | '/ai-hotboard/'
    | '/chat/'
    | '/settings/'
    | '/ai-hotboard/intake/hermes-strategy'
    | '/ai-hotboard/intake/xiaoj-execution'
    | '/ai-hotboard/source/$source'
    | '/ai-hotboard/sources/health'
    | '/ai-hotboard/strategy/$line'
    | '/ai-hotboard/view/all'
    | '/ai-hotboard/view/bookmarks'
    | '/ai-hotboard/view/low-follower'
    | '/api/auth/email'
    | '/api/auth/logout'
    | '/api/auth/password'
    | '/api/hermes-jobs/$jobId'
    | '/api/hermes-proxy/$'
    | '/api/hermes-tasks/$taskId'
    | '/api/hotboard/feed'
    | '/api/hotboard/intake'
    | '/api/hotboard/strategy'
    | '/api/hotboard/vote'
    | '/api/knowledge/config'
    | '/api/knowledge/graph'
    | '/api/knowledge/list'
    | '/api/knowledge/read'
    | '/api/knowledge/search'
    | '/api/knowledge/sync'
    | '/api/mcp/reload'
    | '/api/mcp/servers'
    | '/api/memory/list'
    | '/api/memory/read'
    | '/api/memory/search'
    | '/api/memory/write'
    | '/api/model/info'
    | '/api/oauth/device-code'
    | '/api/oauth/poll-token'
    | '/api/profiles/activate'
    | '/api/profiles/create'
    | '/api/profiles/delete'
    | '/api/profiles/list'
    | '/api/profiles/read'
    | '/api/profiles/rename'
    | '/api/profiles/update'
    | '/api/sessions/send'
    | '/api/skills/hub-search'
    | '/api/skills/install'
    | '/api/skills/toggle'
    | '/api/skills/uninstall'
    | '/api/sources/health'
    | '/auth/email/verify'
    | '/auth/feishu/callback'
    | '/api/hotboard/vote/aggregate'
    | '/api/hotboard/wechat/feed'
    | '/api/hotboard/wechat/ingest'
    | '/api/hotboard/zara/feed'
    | '/api/hotboard/zara/refresh'
    | '/api/sessions/$sessionKey/active-run'
    | '/api/sessions/$sessionKey/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/conductor'
    | '/dashboard'
    | '/files'
    | '/jobs'
    | '/memory'
    | '/operations'
    | '/profiles'
    | '/skills'
    | '/tasks'
    | '/terminal'
    | '/ai-hotboard/iteration'
    | '/ai-hotboard/logout'
    | '/ai-hotboard/system'
    | '/ai-hotboard/user'
    | '/api/auth'
    | '/api/auth-check'
    | '/api/chat-events'
    | '/api/conductor-spawn'
    | '/api/conductor-stop'
    | '/api/connection-status'
    | '/api/context-usage'
    | '/api/crew-status'
    | '/api/events'
    | '/api/files'
    | '/api/gateway-status'
    | '/api/hermes-config'
    | '/api/hermes-jobs'
    | '/api/hermes-tasks'
    | '/api/hermes-tasks-assignees'
    | '/api/history'
    | '/api/local-providers'
    | '/api/memory'
    | '/api/models'
    | '/api/paths'
    | '/api/ping'
    | '/api/preview-file'
    | '/api/send'
    | '/api/send-stream'
    | '/api/session-history'
    | '/api/session-send'
    | '/api/session-status'
    | '/api/sessions'
    | '/api/skills'
    | '/api/start-agent'
    | '/api/start-hermes'
    | '/api/terminal-close'
    | '/api/terminal-input'
    | '/api/terminal-resize'
    | '/api/terminal-stream'
    | '/api/whoami'
    | '/api/workspace'
    | '/chat/$sessionKey'
    | '/settings/mcp'
    | '/settings/providers'
    | '/ai-hotboard'
    | '/chat'
    | '/settings'
    | '/ai-hotboard/intake/hermes-strategy'
    | '/ai-hotboard/intake/xiaoj-execution'
    | '/ai-hotboard/source/$source'
    | '/ai-hotboard/sources/health'
    | '/ai-hotboard/strategy/$line'
    | '/ai-hotboard/view/all'
    | '/ai-hotboard/view/bookmarks'
    | '/ai-hotboard/view/low-follower'
    | '/api/auth/email'
    | '/api/auth/logout'
    | '/api/auth/password'
    | '/api/hermes-jobs/$jobId'
    | '/api/hermes-proxy/$'
    | '/api/hermes-tasks/$taskId'
    | '/api/hotboard/feed'
    | '/api/hotboard/intake'
    | '/api/hotboard/strategy'
    | '/api/hotboard/vote'
    | '/api/knowledge/config'
    | '/api/knowledge/graph'
    | '/api/knowledge/list'
    | '/api/knowledge/read'
    | '/api/knowledge/search'
    | '/api/knowledge/sync'
    | '/api/mcp/reload'
    | '/api/mcp/servers'
    | '/api/memory/list'
    | '/api/memory/read'
    | '/api/memory/search'
    | '/api/memory/write'
    | '/api/model/info'
    | '/api/oauth/device-code'
    | '/api/oauth/poll-token'
    | '/api/profiles/activate'
    | '/api/profiles/create'
    | '/api/profiles/delete'
    | '/api/profiles/list'
    | '/api/profiles/read'
    | '/api/profiles/rename'
    | '/api/profiles/update'
    | '/api/sessions/send'
    | '/api/skills/hub-search'
    | '/api/skills/install'
    | '/api/skills/toggle'
    | '/api/skills/uninstall'
    | '/api/sources/health'
    | '/auth/email/verify'
    | '/auth/feishu/callback'
    | '/api/hotboard/vote/aggregate'
    | '/api/hotboard/wechat/feed'
    | '/api/hotboard/wechat/ingest'
    | '/api/hotboard/zara/feed'
    | '/api/hotboard/zara/refresh'
    | '/api/sessions/$sessionKey/active-run'
    | '/api/sessions/$sessionKey/status'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/ai-hotboard'
    | '/conductor'
    | '/dashboard'
    | '/files'
    | '/jobs'
    | '/memory'
    | '/operations'
    | '/profiles'
    | '/settings'
    | '/skills'
    | '/tasks'
    | '/terminal'
    | '/ai-hotboard/iteration'
    | '/ai-hotboard/logout'
    | '/ai-hotboard/system'
    | '/ai-hotboard/user'
    | '/api/auth'
    | '/api/auth-check'
    | '/api/chat-events'
    | '/api/conductor-spawn'
    | '/api/conductor-stop'
    | '/api/connection-status'
    | '/api/context-usage'
    | '/api/crew-status'
    | '/api/events'
    | '/api/files'
    | '/api/gateway-status'
    | '/api/hermes-config'
    | '/api/hermes-jobs'
    | '/api/hermes-tasks'
    | '/api/hermes-tasks-assignees'
    | '/api/history'
    | '/api/local-providers'
    | '/api/memory'
    | '/api/models'
    | '/api/paths'
    | '/api/ping'
    | '/api/preview-file'
    | '/api/send'
    | '/api/send-stream'
    | '/api/session-history'
    | '/api/session-send'
    | '/api/session-status'
    | '/api/sessions'
    | '/api/skills'
    | '/api/start-agent'
    | '/api/start-hermes'
    | '/api/terminal-close'
    | '/api/terminal-input'
    | '/api/terminal-resize'
    | '/api/terminal-stream'
    | '/api/whoami'
    | '/api/workspace'
    | '/chat/$sessionKey'
    | '/settings/mcp'
    | '/settings/providers'
    | '/ai-hotboard/'
    | '/chat/'
    | '/settings/'
    | '/ai-hotboard/intake/hermes-strategy'
    | '/ai-hotboard/intake/xiaoj-execution'
    | '/ai-hotboard/source/$source'
    | '/ai-hotboard/sources/health'
    | '/ai-hotboard/strategy/$line'
    | '/ai-hotboard/view/all'
    | '/ai-hotboard/view/bookmarks'
    | '/ai-hotboard/view/low-follower'
    | '/api/auth/email'
    | '/api/auth/logout'
    | '/api/auth/password'
    | '/api/hermes-jobs/$jobId'
    | '/api/hermes-proxy/$'
    | '/api/hermes-tasks/$taskId'
    | '/api/hotboard/feed'
    | '/api/hotboard/intake'
    | '/api/hotboard/strategy'
    | '/api/hotboard/vote'
    | '/api/knowledge/config'
    | '/api/knowledge/graph'
    | '/api/knowledge/list'
    | '/api/knowledge/read'
    | '/api/knowledge/search'
    | '/api/knowledge/sync'
    | '/api/mcp/reload'
    | '/api/mcp/servers'
    | '/api/memory/list'
    | '/api/memory/read'
    | '/api/memory/search'
    | '/api/memory/write'
    | '/api/model/info'
    | '/api/oauth/device-code'
    | '/api/oauth/poll-token'
    | '/api/profiles/activate'
    | '/api/profiles/create'
    | '/api/profiles/delete'
    | '/api/profiles/list'
    | '/api/profiles/read'
    | '/api/profiles/rename'
    | '/api/profiles/update'
    | '/api/sessions/send'
    | '/api/skills/hub-search'
    | '/api/skills/install'
    | '/api/skills/toggle'
    | '/api/skills/uninstall'
    | '/api/sources/health'
    | '/auth/email/verify'
    | '/auth/feishu/callback'
    | '/api/hotboard/vote/aggregate'
    | '/api/hotboard/wechat/feed'
    | '/api/hotboard/wechat/ingest'
    | '/api/hotboard/zara/feed'
    | '/api/hotboard/zara/refresh'
    | '/api/sessions/$sessionKey/active-run'
    | '/api/sessions/$sessionKey/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AiHotboardRoute: typeof AiHotboardRouteWithChildren
  ConductorRoute: typeof ConductorRoute
  DashboardRoute: typeof DashboardRoute
  FilesRoute: typeof FilesRoute
  JobsRoute: typeof JobsRoute
  MemoryRoute: typeof MemoryRoute
  OperationsRoute: typeof OperationsRoute
  ProfilesRoute: typeof ProfilesRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SkillsRoute: typeof SkillsRoute
  TasksRoute: typeof TasksRoute
  TerminalRoute: typeof TerminalRoute
  ApiAuthRoute: typeof ApiAuthRouteWithChildren
  ApiAuthCheckRoute: typeof ApiAuthCheckRoute
  ApiChatEventsRoute: typeof ApiChatEventsRoute
  ApiConductorSpawnRoute: typeof ApiConductorSpawnRoute
  ApiConductorStopRoute: typeof ApiConductorStopRoute
  ApiConnectionStatusRoute: typeof ApiConnectionStatusRoute
  ApiContextUsageRoute: typeof ApiContextUsageRoute
  ApiCrewStatusRoute: typeof ApiCrewStatusRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiFilesRoute: typeof ApiFilesRoute
  ApiGatewayStatusRoute: typeof ApiGatewayStatusRoute
  ApiHermesConfigRoute: typeof ApiHermesConfigRoute
  ApiHermesJobsRoute: typeof ApiHermesJobsRouteWithChildren
  ApiHermesTasksRoute: typeof ApiHermesTasksRouteWithChildren
  ApiHermesTasksAssigneesRoute: typeof ApiHermesTasksAssigneesRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiLocalProvidersRoute: typeof ApiLocalProvidersRoute
  ApiMemoryRoute: typeof ApiMemoryRouteWithChildren
  ApiModelsRoute: typeof ApiModelsRoute
  ApiPathsRoute: typeof ApiPathsRoute
  ApiPingRoute: typeof ApiPingRoute
  ApiPreviewFileRoute: typeof ApiPreviewFileRoute
  ApiSendRoute: typeof ApiSendRoute
  ApiSendStreamRoute: typeof ApiSendStreamRoute
  ApiSessionHistoryRoute: typeof ApiSessionHistoryRoute
  ApiSessionSendRoute: typeof ApiSessionSendRoute
  ApiSessionStatusRoute: typeof ApiSessionStatusRoute
  ApiSessionsRoute: typeof ApiSessionsRouteWithChildren
  ApiSkillsRoute: typeof ApiSkillsRouteWithChildren
  ApiStartAgentRoute: typeof ApiStartAgentRoute
  ApiStartHermesRoute: typeof ApiStartHermesRoute
  ApiTerminalCloseRoute: typeof ApiTerminalCloseRoute
  ApiTerminalInputRoute: typeof ApiTerminalInputRoute
  ApiTerminalResizeRoute: typeof ApiTerminalResizeRoute
  ApiTerminalStreamRoute: typeof ApiTerminalStreamRoute
  ApiWhoamiRoute: typeof ApiWhoamiRoute
  ApiWorkspaceRoute: typeof ApiWorkspaceRoute
  ChatSessionKeyRoute: typeof ChatSessionKeyRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ApiHermesProxySplatRoute: typeof ApiHermesProxySplatRoute
  ApiHotboardFeedRoute: typeof ApiHotboardFeedRoute
  ApiHotboardIntakeRoute: typeof ApiHotboardIntakeRoute
  ApiHotboardStrategyRoute: typeof ApiHotboardStrategyRoute
  ApiHotboardVoteRoute: typeof ApiHotboardVoteRouteWithChildren
  ApiKnowledgeConfigRoute: typeof ApiKnowledgeConfigRoute
  ApiKnowledgeGraphRoute: typeof ApiKnowledgeGraphRoute
  ApiKnowledgeListRoute: typeof ApiKnowledgeListRoute
  ApiKnowledgeReadRoute: typeof ApiKnowledgeReadRoute
  ApiKnowledgeSearchRoute: typeof ApiKnowledgeSearchRoute
  ApiKnowledgeSyncRoute: typeof ApiKnowledgeSyncRoute
  ApiMcpReloadRoute: typeof ApiMcpReloadRoute
  ApiMcpServersRoute: typeof ApiMcpServersRoute
  ApiModelInfoRoute: typeof ApiModelInfoRoute
  ApiOauthDeviceCodeRoute: typeof ApiOauthDeviceCodeRoute
  ApiOauthPollTokenRoute: typeof ApiOauthPollTokenRoute
  ApiProfilesActivateRoute: typeof ApiProfilesActivateRoute
  ApiProfilesCreateRoute: typeof ApiProfilesCreateRoute
  ApiProfilesDeleteRoute: typeof ApiProfilesDeleteRoute
  ApiProfilesListRoute: typeof ApiProfilesListRoute
  ApiProfilesReadRoute: typeof ApiProfilesReadRoute
  ApiProfilesRenameRoute: typeof ApiProfilesRenameRoute
  ApiProfilesUpdateRoute: typeof ApiProfilesUpdateRoute
  ApiSourcesHealthRoute: typeof ApiSourcesHealthRoute
  AuthEmailVerifyRoute: typeof AuthEmailVerifyRoute
  AuthFeishuCallbackRoute: typeof AuthFeishuCallbackRoute
  ApiHotboardWechatFeedRoute: typeof ApiHotboardWechatFeedRoute
  ApiHotboardWechatIngestRoute: typeof ApiHotboardWechatIngestRoute
  ApiHotboardZaraFeedRoute: typeof ApiHotboardZaraFeedRoute
  ApiHotboardZaraRefreshRoute: typeof ApiHotboardZaraRefreshRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conductor': {
      id: '/conductor'
      path: '/conductor'
      fullPath: '/conductor'
      preLoaderRoute: typeof ConductorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-hotboard': {
      id: '/ai-hotboard'
      path: '/ai-hotboard'
      fullPath: '/ai-hotboard'
      preLoaderRoute: typeof AiHotboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-hotboard/': {
      id: '/ai-hotboard/'
      path: '/'
      fullPath: '/ai-hotboard/'
      preLoaderRoute: typeof AiHotboardIndexRouteImport
      parentRoute: typeof AiHotboardRoute
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/mcp': {
      id: '/settings/mcp'
      path: '/mcp'
      fullPath: '/settings/mcp'
      preLoaderRoute: typeof SettingsMcpRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/chat/$sessionKey': {
      id: '/chat/$sessionKey'
      path: '/chat/$sessionKey'
      fullPath: '/chat/$sessionKey'
      preLoaderRoute: typeof ChatSessionKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace': {
      id: '/api/workspace'
      path: '/api/workspace'
      fullPath: '/api/workspace'
      preLoaderRoute: typeof ApiWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whoami': {
      id: '/api/whoami'
      path: '/api/whoami'
      fullPath: '/api/whoami'
      preLoaderRoute: typeof ApiWhoamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terminal-stream': {
      id: '/api/terminal-stream'
      path: '/api/terminal-stream'
      fullPath: '/api/terminal-stream'
      preLoaderRoute: typeof ApiTerminalStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terminal-resize': {
      id: '/api/terminal-resize'
      path: '/api/terminal-resize'
      fullPath: '/api/terminal-resize'
      preLoaderRoute: typeof ApiTerminalResizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terminal-input': {
      id: '/api/terminal-input'
      path: '/api/terminal-input'
      fullPath: '/api/terminal-input'
      preLoaderRoute: typeof ApiTerminalInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terminal-close': {
      id: '/api/terminal-close'
      path: '/api/terminal-close'
      fullPath: '/api/terminal-close'
      preLoaderRoute: typeof ApiTerminalCloseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/start-hermes': {
      id: '/api/start-hermes'
      path: '/api/start-hermes'
      fullPath: '/api/start-hermes'
      preLoaderRoute: typeof ApiStartHermesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/start-agent': {
      id: '/api/start-agent'
      path: '/api/start-agent'
      fullPath: '/api/start-agent'
      preLoaderRoute: typeof ApiStartAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skills': {
      id: '/api/skills'
      path: '/api/skills'
      fullPath: '/api/skills'
      preLoaderRoute: typeof ApiSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session-status': {
      id: '/api/session-status'
      path: '/api/session-status'
      fullPath: '/api/session-status'
      preLoaderRoute: typeof ApiSessionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session-send': {
      id: '/api/session-send'
      path: '/api/session-send'
      fullPath: '/api/session-send'
      preLoaderRoute: typeof ApiSessionSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session-history': {
      id: '/api/session-history'
      path: '/api/session-history'
      fullPath: '/api/session-history'
      preLoaderRoute: typeof ApiSessionHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-stream': {
      id: '/api/send-stream'
      path: '/api/send-stream'
      fullPath: '/api/send-stream'
      preLoaderRoute: typeof ApiSendStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send': {
      id: '/api/send'
      path: '/api/send'
      fullPath: '/api/send'
      preLoaderRoute: typeof ApiSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preview-file': {
      id: '/api/preview-file'
      path: '/api/preview-file'
      fullPath: '/api/preview-file'
      preLoaderRoute: typeof ApiPreviewFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paths': {
      id: '/api/paths'
      path: '/api/paths'
      fullPath: '/api/paths'
      preLoaderRoute: typeof ApiPathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory': {
      id: '/api/memory'
      path: '/api/memory'
      fullPath: '/api/memory'
      preLoaderRoute: typeof ApiMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/local-providers': {
      id: '/api/local-providers'
      path: '/api/local-providers'
      fullPath: '/api/local-providers'
      preLoaderRoute: typeof ApiLocalProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes-tasks-assignees': {
      id: '/api/hermes-tasks-assignees'
      path: '/api/hermes-tasks-assignees'
      fullPath: '/api/hermes-tasks-assignees'
      preLoaderRoute: typeof ApiHermesTasksAssigneesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes-tasks': {
      id: '/api/hermes-tasks'
      path: '/api/hermes-tasks'
      fullPath: '/api/hermes-tasks'
      preLoaderRoute: typeof ApiHermesTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes-jobs': {
      id: '/api/hermes-jobs'
      path: '/api/hermes-jobs'
      fullPath: '/api/hermes-jobs'
      preLoaderRoute: typeof ApiHermesJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes-config': {
      id: '/api/hermes-config'
      path: '/api/hermes-config'
      fullPath: '/api/hermes-config'
      preLoaderRoute: typeof ApiHermesConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gateway-status': {
      id: '/api/gateway-status'
      path: '/api/gateway-status'
      fullPath: '/api/gateway-status'
      preLoaderRoute: typeof ApiGatewayStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crew-status': {
      id: '/api/crew-status'
      path: '/api/crew-status'
      fullPath: '/api/crew-status'
      preLoaderRoute: typeof ApiCrewStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/context-usage': {
      id: '/api/context-usage'
      path: '/api/context-usage'
      fullPath: '/api/context-usage'
      preLoaderRoute: typeof ApiContextUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connection-status': {
      id: '/api/connection-status'
      path: '/api/connection-status'
      fullPath: '/api/connection-status'
      preLoaderRoute: typeof ApiConnectionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conductor-stop': {
      id: '/api/conductor-stop'
      path: '/api/conductor-stop'
      fullPath: '/api/conductor-stop'
      preLoaderRoute: typeof ApiConductorStopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conductor-spawn': {
      id: '/api/conductor-spawn'
      path: '/api/conductor-spawn'
      fullPath: '/api/conductor-spawn'
      preLoaderRoute: typeof ApiConductorSpawnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-events': {
      id: '/api/chat-events'
      path: '/api/chat-events'
      fullPath: '/api/chat-events'
      preLoaderRoute: typeof ApiChatEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth-check': {
      id: '/api/auth-check'
      path: '/api/auth-check'
      fullPath: '/api/auth-check'
      preLoaderRoute: typeof ApiAuthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-hotboard/user': {
      id: '/ai-hotboard/user'
      path: '/user'
      fullPath: '/ai-hotboard/user'
      preLoaderRoute: typeof AiHotboardUserRouteImport
      parentRoute: typeof AiHotboardRoute
    }
    '/ai-hotboard/system': {
      id: '/ai-hotboard/system'
      path: '/system'
      fullPath: '/ai-hotboard/system'
      preLoaderRoute: typeof AiHotboardSystemRouteImport
      parentRoute: typeof AiHotboardRoute
    }
    '/ai-hotboard/logout': {
      id: '/ai-hotboard/logout'
      path: '/logout'
      fullPath: '/ai-hotboard/logout'
      preLoaderRoute: typeof AiHotboardLogoutRouteImport
      parentRoute: typeof AiHotboardRoute
    }
    '/ai-hotboard/iteration': {
      id: '/ai-hotboard/iteration'
      path: '/iteration'
      fullPath: '/ai-hotboard/iteration'
      preLoaderRoute: typeof AiHotboardIterationRouteImport
      parentRoute: typeof AiHotboardRoute
    }
    '/auth/feishu/callback': {
      id: '/auth/feishu/callback'
      path: '/auth/feishu/callback'
      fullPath: '/auth/feishu/callback'
      preLoaderRoute: typeof AuthFeishuCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/email/verify': {
      id: '/auth/email/verify'
      path: '/auth/email/verify'
      fullPath: '/auth/email/verify'
      preLoaderRoute: typeof AuthEmailVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sources/health': {
      id: '/api/sources/health'
      path: '/api/sources/health'
      fullPath: '/api/sources/health'
      preLoaderRoute: typeof ApiSourcesHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skills/uninstall': {
      id: '/api/skills/uninstall'
      path: '/uninstall'
      fullPath: '/api/skills/uninstall'
      preLoaderRoute: typeof ApiSkillsUninstallRouteImport
      parentRoute: typeof ApiSkillsRoute
    }
    '/api/skills/toggle': {
      id: '/api/skills/toggle'
      path: '/toggle'
      fullPath: '/api/skills/toggle'
      preLoaderRoute: typeof ApiSkillsToggleRouteImport
      parentRoute: typeof ApiSkillsRoute
    }
    '/api/skills/install': {
      id: '/api/skills/install'
      path: '/install'
      fullPath: '/api/skills/install'
      preLoaderRoute: typeof ApiSkillsInstallRouteImport
      parentRoute: typeof ApiSkillsRoute
    }
    '/api/skills/hub-search': {
      id: '/api/skills/hub-search'
      path: '/hub-search'
      fullPath: '/api/skills/hub-search'
      preLoaderRoute: typeof ApiSkillsHubSearchRouteImport
      parentRoute: typeof ApiSkillsRoute
    }
    '/api/sessions/send': {
      id: '/api/sessions/send'
      path: '/send'
      fullPath: '/api/sessions/send'
      preLoaderRoute: typeof ApiSessionsSendRouteImport
      parentRoute: typeof ApiSessionsRoute
    }
    '/api/profiles/update': {
      id: '/api/profiles/update'
      path: '/api/profiles/update'
      fullPath: '/api/profiles/update'
      preLoaderRoute: typeof ApiProfilesUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profiles/rename': {
      id: '/api/profiles/rename'
      path: '/api/profiles/rename'
      fullPath: '/api/profiles/rename'
      preLoaderRoute: typeof ApiProfilesRenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profiles/read': {
      id: '/api/profiles/read'
      path: '/api/profiles/read'
      fullPath: '/api/profiles/read'
      preLoaderRoute: typeof ApiProfilesReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profiles/list': {
      id: '/api/profiles/list'
      path: '/api/profiles/list'
      fullPath: '/api/profiles/list'
      preLoaderRoute: typeof ApiProfilesListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profiles/delete': {
      id: '/api/profiles/delete'
      path: '/api/profiles/delete'
      fullPath: '/api/profiles/delete'
      preLoaderRoute: typeof ApiProfilesDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profiles/create': {
      id: '/api/profiles/create'
      path: '/api/profiles/create'
      fullPath: '/api/profiles/create'
      preLoaderRoute: typeof ApiProfilesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profiles/activate': {
      id: '/api/profiles/activate'
      path: '/api/profiles/activate'
      fullPath: '/api/profiles/activate'
      preLoaderRoute: typeof ApiProfilesActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/poll-token': {
      id: '/api/oauth/poll-token'
      path: '/api/oauth/poll-token'
      fullPath: '/api/oauth/poll-token'
      preLoaderRoute: typeof ApiOauthPollTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/device-code': {
      id: '/api/oauth/device-code'
      path: '/api/oauth/device-code'
      fullPath: '/api/oauth/device-code'
      preLoaderRoute: typeof ApiOauthDeviceCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/model/info': {
      id: '/api/model/info'
      path: '/api/model/info'
      fullPath: '/api/model/info'
      preLoaderRoute: typeof ApiModelInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory/write': {
      id: '/api/memory/write'
      path: '/write'
      fullPath: '/api/memory/write'
      preLoaderRoute: typeof ApiMemoryWriteRouteImport
      parentRoute: typeof ApiMemoryRoute
    }
    '/api/memory/search': {
      id: '/api/memory/search'
      path: '/search'
      fullPath: '/api/memory/search'
      preLoaderRoute: typeof ApiMemorySearchRouteImport
      parentRoute: typeof ApiMemoryRoute
    }
    '/api/memory/read': {
      id: '/api/memory/read'
      path: '/read'
      fullPath: '/api/memory/read'
      preLoaderRoute: typeof ApiMemoryReadRouteImport
      parentRoute: typeof ApiMemoryRoute
    }
    '/api/memory/list': {
      id: '/api/memory/list'
      path: '/list'
      fullPath: '/api/memory/list'
      preLoaderRoute: typeof ApiMemoryListRouteImport
      parentRoute: typeof ApiMemoryRoute
    }
    '/api/mcp/servers': {
      id: '/api/mcp/servers'
      path: '/api/mcp/servers'
      fullPath: '/api/mcp/servers'
      preLoaderRoute: typeof ApiMcpServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/reload': {
      id: '/api/mcp/reload'
      path: '/api/mcp/reload'
      fullPath: '/api/mcp/reload'
      preLoaderRoute: typeof ApiMcpReloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge/sync': {
      id: '/api/knowledge/sync'
      path: '/api/knowledge/sync'
      fullPath: '/api/knowledge/sync'
      preLoaderRoute: typeof ApiKnowledgeSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge/search': {
      id: '/api/knowledge/search'
      path: '/api/knowledge/search'
      fullPath: '/api/knowledge/search'
      preLoaderRoute: typeof ApiKnowledgeSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge/read': {
      id: '/api/knowledge/read'
      path: '/api/knowledge/read'
      fullPath: '/api/knowledge/read'
      preLoaderRoute: typeof ApiKnowledgeReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge/list': {
      id: '/api/knowledge/list'
      path: '/api/knowledge/list'
      fullPath: '/api/knowledge/list'
      preLoaderRoute: typeof ApiKnowledgeListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge/graph': {
      id: '/api/knowledge/graph'
      path: '/api/knowledge/graph'
      fullPath: '/api/knowledge/graph'
      preLoaderRoute: typeof ApiKnowledgeGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge/config': {
      id: '/api/knowledge/config'
      path: '/api/knowledge/config'
      fullPath: '/api/knowledge/config'
      preLoaderRoute: typeof ApiKnowledgeConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hotboard/vote': {
      id: '/api/hotboard/vote'
      path: '/api/hotboard/vote'
      fullPath: '/api/hotboard/vote'
      preLoaderRoute: typeof ApiHotboardVoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hotboard/strategy': {
      id: '/api/hotboard/strategy'
      path: '/api/hotboard/strategy'
      fullPath: '/api/hotboard/strategy'
      preLoaderRoute: typeof ApiHotboardStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hotboard/intake': {
      id: '/api/hotboard/intake'
      path: '/api/hotboard/intake'
      fullPath: '/api/hotboard/intake'
      preLoaderRoute: typeof ApiHotboardIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hotboard/feed': {
      id: '/api/hotboard/feed'
      path: '/api/hotboard/feed'
      fullPath: '/api/hotboard/feed'
      preLoaderRoute: typeof ApiHotboardFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes-tasks/$taskId': {
      id: '/api/hermes-tasks/$taskId'
      path: '/$taskId'
      fullPath: '/api/hermes-tasks/$taskId'
      preLoaderRoute: typeof ApiHermesTasksTaskIdRouteImport
      parentRoute: typeof ApiHermesTasksRoute
    }
    '/api/hermes-proxy/$': {
      id: '/api/hermes-proxy/$'
      path: '/api/hermes-proxy/$'
      fullPath: '/api/hermes-proxy/$'
      preLoaderRoute: typeof ApiHermesProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes-jobs/$jobId': {
      id: '/api/hermes-jobs/$jobId'
      path: '/$jobId'
      fullPath: '/api/hermes-jobs/$jobId'
      preLoaderRoute: typeof ApiHermesJobsJobIdRouteImport
      parentRoute: typeof ApiHermesJobsRoute
    }
    '/api/auth/password': {
      id: '/api/auth/password'
      path: '/password'
      fullPath: '/api/auth/password'
      preLoaderRoute: typeof ApiAuthPasswordRouteImport
      parentRoute: typeof ApiAuthRoute
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof ApiAuthRoute
    }
    '/api/auth/email': {
      id: '/api/auth/email'
      path: '/email'
      fullPath: '/api/auth/email'
      preLoaderRoute: typeof ApiAuthEmailRouteImport
      parentRoute: typeof ApiAuthRoute
    }
    '/ai-hotboard/view/low-follower': {
      id: '/ai-hotboard/view/low-follower'
      path: '/view/low-follower'
      fullPath: '/ai-hotboard/view/low-follower'
      preLoaderRoute: typeof AiHotboardViewLowFollowerRouteImport
      parentRoute: typeof AiHotboardRoute
    }
    '/ai-hotboard/view/bookmarks': {
      id: '/ai-hotboard/view/bookmarks'
      path: '/view/bookmarks'
      fullPath: '/ai-hotboard/view/bookmarks'
      preLoaderRoute: typeof AiHotboardViewBookmarksRouteImport
      parentRoute: typeof AiHotboardRoute
    }
    '/ai-hotboard/view/all': {
      id: '/ai-hotboard/view/all'
      path: '/view/all'
      fullPath: '/ai-hotboard/view/all'
      preLoaderRoute: typeof AiHotboardViewAllRouteImport
      parentRoute: typeof AiHotboardRoute
    }
    '/ai-hotboard/strategy/$line': {
      id: '/ai-hotboard/strategy/$line'
      path: '/strategy/$line'
      fullPath: '/ai-hotboard/strategy/$line'
      preLoaderRoute: typeof AiHotboardStrategyLineRouteImport
      parentRoute: typeof AiHotboardRoute
    }
    '/ai-hotboard/sources/health': {
      id: '/ai-hotboard/sources/health'
      path: '/sources/health'
      fullPath: '/ai-hotboard/sources/health'
      preLoaderRoute: typeof AiHotboardSourcesHealthRouteImport
      parentRoute: typeof AiHotboardRoute
    }
    '/ai-hotboard/source/$source': {
      id: '/ai-hotboard/source/$source'
      path: '/source/$source'
      fullPath: '/ai-hotboard/source/$source'
      preLoaderRoute: typeof AiHotboardSourceSourceRouteImport
      parentRoute: typeof AiHotboardRoute
    }
    '/ai-hotboard/intake/xiaoj-execution': {
      id: '/ai-hotboard/intake/xiaoj-execution'
      path: '/intake/xiaoj-execution'
      fullPath: '/ai-hotboard/intake/xiaoj-execution'
      preLoaderRoute: typeof AiHotboardIntakeXiaojExecutionRouteImport
      parentRoute: typeof AiHotboardRoute
    }
    '/ai-hotboard/intake/hermes-strategy': {
      id: '/ai-hotboard/intake/hermes-strategy'
      path: '/intake/hermes-strategy'
      fullPath: '/ai-hotboard/intake/hermes-strategy'
      preLoaderRoute: typeof AiHotboardIntakeHermesStrategyRouteImport
      parentRoute: typeof AiHotboardRoute
    }
    '/api/sessions/$sessionKey/status': {
      id: '/api/sessions/$sessionKey/status'
      path: '/$sessionKey/status'
      fullPath: '/api/sessions/$sessionKey/status'
      preLoaderRoute: typeof ApiSessionsSessionKeyStatusRouteImport
      parentRoute: typeof ApiSessionsRoute
    }
    '/api/sessions/$sessionKey/active-run': {
      id: '/api/sessions/$sessionKey/active-run'
      path: '/$sessionKey/active-run'
      fullPath: '/api/sessions/$sessionKey/active-run'
      preLoaderRoute: typeof ApiSessionsSessionKeyActiveRunRouteImport
      parentRoute: typeof ApiSessionsRoute
    }
    '/api/hotboard/zara/refresh': {
      id: '/api/hotboard/zara/refresh'
      path: '/api/hotboard/zara/refresh'
      fullPath: '/api/hotboard/zara/refresh'
      preLoaderRoute: typeof ApiHotboardZaraRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hotboard/zara/feed': {
      id: '/api/hotboard/zara/feed'
      path: '/api/hotboard/zara/feed'
      fullPath: '/api/hotboard/zara/feed'
      preLoaderRoute: typeof ApiHotboardZaraFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hotboard/wechat/ingest': {
      id: '/api/hotboard/wechat/ingest'
      path: '/api/hotboard/wechat/ingest'
      fullPath: '/api/hotboard/wechat/ingest'
      preLoaderRoute: typeof ApiHotboardWechatIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hotboard/wechat/feed': {
      id: '/api/hotboard/wechat/feed'
      path: '/api/hotboard/wechat/feed'
      fullPath: '/api/hotboard/wechat/feed'
      preLoaderRoute: typeof ApiHotboardWechatFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hotboard/vote/aggregate': {
      id: '/api/hotboard/vote/aggregate'
      path: '/aggregate'
      fullPath: '/api/hotboard/vote/aggregate'
      preLoaderRoute: typeof ApiHotboardVoteAggregateRouteImport
      parentRoute: typeof ApiHotboardVoteRoute
    }
  }
}

interface AiHotboardRouteChildren {
  AiHotboardIterationRoute: typeof AiHotboardIterationRoute
  AiHotboardLogoutRoute: typeof AiHotboardLogoutRoute
  AiHotboardSystemRoute: typeof AiHotboardSystemRoute
  AiHotboardUserRoute: typeof AiHotboardUserRoute
  AiHotboardIndexRoute: typeof AiHotboardIndexRoute
  AiHotboardIntakeHermesStrategyRoute: typeof AiHotboardIntakeHermesStrategyRoute
  AiHotboardIntakeXiaojExecutionRoute: typeof AiHotboardIntakeXiaojExecutionRoute
  AiHotboardSourceSourceRoute: typeof AiHotboardSourceSourceRoute
  AiHotboardSourcesHealthRoute: typeof AiHotboardSourcesHealthRoute
  AiHotboardStrategyLineRoute: typeof AiHotboardStrategyLineRoute
  AiHotboardViewAllRoute: typeof AiHotboardViewAllRoute
  AiHotboardViewBookmarksRoute: typeof AiHotboardViewBookmarksRoute
  AiHotboardViewLowFollowerRoute: typeof AiHotboardViewLowFollowerRoute
}

const AiHotboardRouteChildren: AiHotboardRouteChildren = {
  AiHotboardIterationRoute: AiHotboardIterationRoute,
  AiHotboardLogoutRoute: AiHotboardLogoutRoute,
  AiHotboardSystemRoute: AiHotboardSystemRoute,
  AiHotboardUserRoute: AiHotboardUserRoute,
  AiHotboardIndexRoute: AiHotboardIndexRoute,
  AiHotboardIntakeHermesStrategyRoute: AiHotboardIntakeHermesStrategyRoute,
  AiHotboardIntakeXiaojExecutionRoute: AiHotboardIntakeXiaojExecutionRoute,
  AiHotboardSourceSourceRoute: AiHotboardSourceSourceRoute,
  AiHotboardSourcesHealthRoute: AiHotboardSourcesHealthRoute,
  AiHotboardStrategyLineRoute: AiHotboardStrategyLineRoute,
  AiHotboardViewAllRoute: AiHotboardViewAllRoute,
  AiHotboardViewBookmarksRoute: AiHotboardViewBookmarksRoute,
  AiHotboardViewLowFollowerRoute: AiHotboardViewLowFollowerRoute,
}

const AiHotboardRouteWithChildren = AiHotboardRoute._addFileChildren(
  AiHotboardRouteChildren,
)

interface SettingsRouteChildren {
  SettingsMcpRoute: typeof SettingsMcpRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsMcpRoute: SettingsMcpRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface ApiAuthRouteChildren {
  ApiAuthEmailRoute: typeof ApiAuthEmailRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthPasswordRoute: typeof ApiAuthPasswordRoute
}

const ApiAuthRouteChildren: ApiAuthRouteChildren = {
  ApiAuthEmailRoute: ApiAuthEmailRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthPasswordRoute: ApiAuthPasswordRoute,
}

const ApiAuthRouteWithChildren =
  ApiAuthRoute._addFileChildren(ApiAuthRouteChildren)

interface ApiHermesJobsRouteChildren {
  ApiHermesJobsJobIdRoute: typeof ApiHermesJobsJobIdRoute
}

const ApiHermesJobsRouteChildren: ApiHermesJobsRouteChildren = {
  ApiHermesJobsJobIdRoute: ApiHermesJobsJobIdRoute,
}

const ApiHermesJobsRouteWithChildren = ApiHermesJobsRoute._addFileChildren(
  ApiHermesJobsRouteChildren,
)

interface ApiHermesTasksRouteChildren {
  ApiHermesTasksTaskIdRoute: typeof ApiHermesTasksTaskIdRoute
}

const ApiHermesTasksRouteChildren: ApiHermesTasksRouteChildren = {
  ApiHermesTasksTaskIdRoute: ApiHermesTasksTaskIdRoute,
}

const ApiHermesTasksRouteWithChildren = ApiHermesTasksRoute._addFileChildren(
  ApiHermesTasksRouteChildren,
)

interface ApiMemoryRouteChildren {
  ApiMemoryListRoute: typeof ApiMemoryListRoute
  ApiMemoryReadRoute: typeof ApiMemoryReadRoute
  ApiMemorySearchRoute: typeof ApiMemorySearchRoute
  ApiMemoryWriteRoute: typeof ApiMemoryWriteRoute
}

const ApiMemoryRouteChildren: ApiMemoryRouteChildren = {
  ApiMemoryListRoute: ApiMemoryListRoute,
  ApiMemoryReadRoute: ApiMemoryReadRoute,
  ApiMemorySearchRoute: ApiMemorySearchRoute,
  ApiMemoryWriteRoute: ApiMemoryWriteRoute,
}

const ApiMemoryRouteWithChildren = ApiMemoryRoute._addFileChildren(
  ApiMemoryRouteChildren,
)

interface ApiSessionsRouteChildren {
  ApiSessionsSendRoute: typeof ApiSessionsSendRoute
  ApiSessionsSessionKeyActiveRunRoute: typeof ApiSessionsSessionKeyActiveRunRoute
  ApiSessionsSessionKeyStatusRoute: typeof ApiSessionsSessionKeyStatusRoute
}

const ApiSessionsRouteChildren: ApiSessionsRouteChildren = {
  ApiSessionsSendRoute: ApiSessionsSendRoute,
  ApiSessionsSessionKeyActiveRunRoute: ApiSessionsSessionKeyActiveRunRoute,
  ApiSessionsSessionKeyStatusRoute: ApiSessionsSessionKeyStatusRoute,
}

const ApiSessionsRouteWithChildren = ApiSessionsRoute._addFileChildren(
  ApiSessionsRouteChildren,
)

interface ApiSkillsRouteChildren {
  ApiSkillsHubSearchRoute: typeof ApiSkillsHubSearchRoute
  ApiSkillsInstallRoute: typeof ApiSkillsInstallRoute
  ApiSkillsToggleRoute: typeof ApiSkillsToggleRoute
  ApiSkillsUninstallRoute: typeof ApiSkillsUninstallRoute
}

const ApiSkillsRouteChildren: ApiSkillsRouteChildren = {
  ApiSkillsHubSearchRoute: ApiSkillsHubSearchRoute,
  ApiSkillsInstallRoute: ApiSkillsInstallRoute,
  ApiSkillsToggleRoute: ApiSkillsToggleRoute,
  ApiSkillsUninstallRoute: ApiSkillsUninstallRoute,
}

const ApiSkillsRouteWithChildren = ApiSkillsRoute._addFileChildren(
  ApiSkillsRouteChildren,
)

interface ApiHotboardVoteRouteChildren {
  ApiHotboardVoteAggregateRoute: typeof ApiHotboardVoteAggregateRoute
}

const ApiHotboardVoteRouteChildren: ApiHotboardVoteRouteChildren = {
  ApiHotboardVoteAggregateRoute: ApiHotboardVoteAggregateRoute,
}

const ApiHotboardVoteRouteWithChildren = ApiHotboardVoteRoute._addFileChildren(
  ApiHotboardVoteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AiHotboardRoute: AiHotboardRouteWithChildren,
  ConductorRoute: ConductorRoute,
  DashboardRoute: DashboardRoute,
  FilesRoute: FilesRoute,
  JobsRoute: JobsRoute,
  MemoryRoute: MemoryRoute,
  OperationsRoute: OperationsRoute,
  ProfilesRoute: ProfilesRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SkillsRoute: SkillsRoute,
  TasksRoute: TasksRoute,
  TerminalRoute: TerminalRoute,
  ApiAuthRoute: ApiAuthRouteWithChildren,
  ApiAuthCheckRoute: ApiAuthCheckRoute,
  ApiChatEventsRoute: ApiChatEventsRoute,
  ApiConductorSpawnRoute: ApiConductorSpawnRoute,
  ApiConductorStopRoute: ApiConductorStopRoute,
  ApiConnectionStatusRoute: ApiConnectionStatusRoute,
  ApiContextUsageRoute: ApiContextUsageRoute,
  ApiCrewStatusRoute: ApiCrewStatusRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiFilesRoute: ApiFilesRoute,
  ApiGatewayStatusRoute: ApiGatewayStatusRoute,
  ApiHermesConfigRoute: ApiHermesConfigRoute,
  ApiHermesJobsRoute: ApiHermesJobsRouteWithChildren,
  ApiHermesTasksRoute: ApiHermesTasksRouteWithChildren,
  ApiHermesTasksAssigneesRoute: ApiHermesTasksAssigneesRoute,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiLocalProvidersRoute: ApiLocalProvidersRoute,
  ApiMemoryRoute: ApiMemoryRouteWithChildren,
  ApiModelsRoute: ApiModelsRoute,
  ApiPathsRoute: ApiPathsRoute,
  ApiPingRoute: ApiPingRoute,
  ApiPreviewFileRoute: ApiPreviewFileRoute,
  ApiSendRoute: ApiSendRoute,
  ApiSendStreamRoute: ApiSendStreamRoute,
  ApiSessionHistoryRoute: ApiSessionHistoryRoute,
  ApiSessionSendRoute: ApiSessionSendRoute,
  ApiSessionStatusRoute: ApiSessionStatusRoute,
  ApiSessionsRoute: ApiSessionsRouteWithChildren,
  ApiSkillsRoute: ApiSkillsRouteWithChildren,
  ApiStartAgentRoute: ApiStartAgentRoute,
  ApiStartHermesRoute: ApiStartHermesRoute,
  ApiTerminalCloseRoute: ApiTerminalCloseRoute,
  ApiTerminalInputRoute: ApiTerminalInputRoute,
  ApiTerminalResizeRoute: ApiTerminalResizeRoute,
  ApiTerminalStreamRoute: ApiTerminalStreamRoute,
  ApiWhoamiRoute: ApiWhoamiRoute,
  ApiWorkspaceRoute: ApiWorkspaceRoute,
  ChatSessionKeyRoute: ChatSessionKeyRoute,
  ChatIndexRoute: ChatIndexRoute,
  ApiHermesProxySplatRoute: ApiHermesProxySplatRoute,
  ApiHotboardFeedRoute: ApiHotboardFeedRoute,
  ApiHotboardIntakeRoute: ApiHotboardIntakeRoute,
  ApiHotboardStrategyRoute: ApiHotboardStrategyRoute,
  ApiHotboardVoteRoute: ApiHotboardVoteRouteWithChildren,
  ApiKnowledgeConfigRoute: ApiKnowledgeConfigRoute,
  ApiKnowledgeGraphRoute: ApiKnowledgeGraphRoute,
  ApiKnowledgeListRoute: ApiKnowledgeListRoute,
  ApiKnowledgeReadRoute: ApiKnowledgeReadRoute,
  ApiKnowledgeSearchRoute: ApiKnowledgeSearchRoute,
  ApiKnowledgeSyncRoute: ApiKnowledgeSyncRoute,
  ApiMcpReloadRoute: ApiMcpReloadRoute,
  ApiMcpServersRoute: ApiMcpServersRoute,
  ApiModelInfoRoute: ApiModelInfoRoute,
  ApiOauthDeviceCodeRoute: ApiOauthDeviceCodeRoute,
  ApiOauthPollTokenRoute: ApiOauthPollTokenRoute,
  ApiProfilesActivateRoute: ApiProfilesActivateRoute,
  ApiProfilesCreateRoute: ApiProfilesCreateRoute,
  ApiProfilesDeleteRoute: ApiProfilesDeleteRoute,
  ApiProfilesListRoute: ApiProfilesListRoute,
  ApiProfilesReadRoute: ApiProfilesReadRoute,
  ApiProfilesRenameRoute: ApiProfilesRenameRoute,
  ApiProfilesUpdateRoute: ApiProfilesUpdateRoute,
  ApiSourcesHealthRoute: ApiSourcesHealthRoute,
  AuthEmailVerifyRoute: AuthEmailVerifyRoute,
  AuthFeishuCallbackRoute: AuthFeishuCallbackRoute,
  ApiHotboardWechatFeedRoute: ApiHotboardWechatFeedRoute,
  ApiHotboardWechatIngestRoute: ApiHotboardWechatIngestRoute,
  ApiHotboardZaraFeedRoute: ApiHotboardZaraFeedRoute,
  ApiHotboardZaraRefreshRoute: ApiHotboardZaraRefreshRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
